#define __SYSCALL_LL_E(x) \
((union { long long ll; long l[2]; }){ .ll = x }).l[0], \
((union { long long ll; long l[2]; }){ .ll = x }).l[1]
#define __SYSCALL_LL_O(x) __SYSCALL_LL_E((x))

struct iovec;
struct rlimit;
struct sched_param;
struct timespec;
struct sockaddr;
struct msghdr;
struct epoll_event;
struct rusage;
struct iocb;

long __syscall_restart_syscall(void);
long __syscall_exit(int error_code);
long __syscall_fork(void);
int __syscall_read(int fd, void* buf, int count);
int __syscall_write(int fd, void* buf, int count);
long __syscall_open(const char* pathname, int flags, ...);
long __syscall_close(int fd);
long __syscall_waitpid(int pid, int* wstatus, int options);
long __syscall_creat(const char* pathname, int mode);
int __syscall_link(const char *oldpath, const char *newpath);
int __syscall_unlink(const char *pathname);
long __syscall_execve(const char* path, char* const argv[], char* const envp[]);
long __syscall_chdir(const char* filename);
long __syscall_time(long* tloc);
long __syscall_mknod(const char* filename, int mode, unsigned dev);
long __syscall_chmod(const char *pathname, int mode);
long __syscall_lchown(const char* filename, int user, int group);
long __syscall_break(void);
long __syscall_oldstat(const char* filename, void* statbuf);
long __syscall_lseek(int fd, long offset, unsigned int whence);
long __syscall_getpid(void);
long __syscall_mount(char* dev_name, char* dir_name, char* type, unsigned long flags, void* data);
long __syscall_umount(char* name);
long __syscall_setuid(int uid);
long __syscall_getuid(void);
long __syscall_stime(long* tptr);
long __syscall_ptrace(long request, long pid, unsigned long addr, unsigned long data, unsigned long addr2);
long __syscall_alarm(unsigned int seconds);
long __syscall_oldfstat(int fd, void* statbuf);
long __syscall_pause(void);
long __syscall_utime(char* filename, void* times);
long __syscall_stty(void);
long __syscall_gtty(void);
int __syscall_access(const char *pathname, int mode);
long __syscall_nice(int increment);
long __syscall_ftime(void);
long __syscall_sync(void);
long __syscall_kill(int pid, int sig);
int __syscall_rename(const char *oldpath, const char *newpath);
int __syscall_mkdir(const char *pathname, int mode);
int __syscall_rmdir(const char *path);
long __syscall_dup(unsigned int fildes);
long __syscall_pipe(int* fildes);
long __syscall_times(void* tbuf);
long __syscall_prof(void);
long __syscall_brk(void* newaddr);
long __syscall_setgid(int gid);
long __syscall_getgid(void);
long __syscall_signal(int sig, void* handler);
long __syscall_geteuid(void);
long __syscall_getegid(void);
long __syscall_acct(const char* name);
long __syscall_umount2(char* name, int flags);
long __syscall_lock(void);
long __syscall_ioctl(long fd, long req, void* arg);
long __syscall_fcntl(unsigned int fd, unsigned int cmd, unsigned long arg);
long __syscall_mpx(void);
long __syscall_setpgid(int pid, int pgid);
long __syscall_ulimit(void);
long __syscall_oldolduname(void* name);
long __syscall_umask(int mode);
long __syscall_chroot(const char* filename);
long __syscall_ustat(unsigned dev, void* ubuf);
long __syscall_dup2(int oldfd, int newfd);
long __syscall_getppid(void);
long __syscall_getpgrp(void);
long __syscall_setsid(void);
long __syscall_sigaction(int sig, const void* act, void* oldact);
long __syscall_sgetmask(void);
long __syscall_ssetmask(long newmask);
long __syscall_setreuid(int ruid, int euid);
long __syscall_setregid(int rgid, int egid);
long __syscall_sigsuspend(const void* mask);
long __syscall_sigpending(void* set);
long __syscall_sethostname(char* name, int len);
long __syscall_setrlimit(unsigned int resource, struct rlimit* rlim);
long __syscall_getrlimit(unsigned int resource, struct rlimit* rlim);
long __syscall_getrusage(int resource, void* rlim);
long __syscall_gettimeofday_time32(void* tv, void* tz);
long __syscall_settimeofday_time32(void* tv, void* tz);
long __syscall_getgroups(int gidsetsize, void* grouplist);
long __syscall_setgroups(int gidsetsize, void* grouplist);
long __syscall_select(int n, void* inp, void* outp, void* exp, void* tvp);
long __syscall_symlink(const char *target, const char *linkpath);
long __syscall_oldlstat(const char* filename, void* statbuf);
long __syscall_readlink(const char* pathname, char* buf, long bufsize);
long __syscall_uselib(const char* library);
long __syscall_swapon(const char* specialfile, int swap_flags);
long __syscall_reboot(int magic1, int magic2, unsigned int cmd);
long __syscall_readdir(unsigned int fd, void* dirent, unsigned int count);
long __syscall_mmap(unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags, unsigned long fd, unsigned long offset);
long __syscall_munmap(long a1, long length);
long __syscall_truncate(const char* path, long length);
long __syscall_ftruncate(unsigned int fd, unsigned long length);
long __syscall_fchmod(unsigned int fd, int mode);
long __syscall_fchown(unsigned int fd, int user, int group);
long __syscall_getpriority(int which, int who);
long __syscall_setpriority(int which, int who, int niceval);
long __syscall_profil(void);
long __syscall_statfs(const char* path, void* buf);
long __syscall_fstatfs(unsigned int fd, void* buf);
long __syscall_ioperm(unsigned long from, unsigned long num, int on);
long __syscall_socketcall(int call, unsigned long* args);
long __syscall_syslog(int type, char* buf, int len);
long __syscall_setitimer(int which, void* value, void* ovalue);
long __syscall_getitimer(int which, void* value);
long __syscall_stat(const char* filename, void* statbuf);
long __syscall_lstat(const char* filename, void* statbuf);
long __syscall_fstat(int fd, void* statbuf);
long __syscall_olduname(void* name);
long __syscall_iopl(unsigned int level);
long __syscall_vhangup(void);
long __syscall_idle(void);
long __syscall_vm86old(void* v86);
long __syscall_wait4(unsigned int pid, int* wstatus, int options, void* rusage);
long __syscall_swapoff(const char* specialfile);
long __syscall_sysinfo(void* info);
long __syscall_ipc(long a1, ...);
long __syscall_fsync(unsigned int fd);
long __syscall_sigreturn(void);
long __syscall_clone(unsigned long flags, unsigned long stack, int* parent_tid, unsigned long tls, int* child_tid);
long __syscall_clone4(int (*func)(void *), void *stack, int flags, void *arg, void *ptid, void *tls, void *ctid);
long __syscall_setdomainname(char* name, int len);
long __syscall_uname(void* utsname);
long __syscall_modify_ldt(int func, void* ptr, unsigned long bytecount);
long __syscall_adjtimex(void* txc_p);
long __syscall_mprotect(long addr, long len, int flags);
long __syscall_sigprocmask(int how, const void* set, void* oldset);
long __syscall_create_module(const char* name, unsigned long size);
long __syscall_init_module(void* umod, unsigned long len, const char* uargs);
long __syscall_delete_module(const char* name_user, unsigned int flags);
long __syscall_get_kernel_syms(void* table);
long __syscall_quotactl(unsigned int cmd, const char* special, int id, void* addr);
long __syscall_getpgid(int pid);
long __syscall_fchdir(unsigned int fd);
long __syscall_bdflush(int func, long data);
long __syscall_sysfs(int option, unsigned long arg1, unsigned long arg2);
long __syscall_personality(unsigned int personality);
long __syscall_afs_syscall(void);
long __syscall_setfsuid(int uid);
long __syscall_setfsgid(int gid);
long __syscall__llseek(unsigned int a1, unsigned long a2, unsigned long a3, long* a4, unsigned int a5);
long __syscall_getdents(int fd, void* buf, long len);
long __syscall__newselect(long nfds, void* readfds, void* writefds, void* exceptfds, void* timeout);
long __syscall_flock(unsigned int fd, unsigned int cmd);
long __syscall_msync(unsigned long start, long len, int flags);
long __syscall_readv(long fd, const struct iovec* ios, long len);
long __syscall_writev(long fd, const struct iovec* ios, long len);
long __syscall_getsid(int pid);
long __syscall_fdatasync(unsigned int fd);
long __syscall__sysctl(void* args);
long __syscall_mlock(unsigned long start, long len);
long __syscall_munlock(unsigned long start, long len);
long __syscall_mlockall(int flags);
long __syscall_munlockall(void);
long __syscall_sched_setparam(int pid, struct sched_param* param);
long __syscall_sched_getparam(int pid, struct sched_param* param);
long __syscall_sched_setscheduler(long pid, int policy, const struct sched_param *param);
long __syscall_sched_getscheduler(int pid);
long __syscall_sched_yield(void);
long __syscall_sched_get_priority_max(int policy);
long __syscall_sched_get_priority_min(int policy);
long __syscall_sched_rr_get_interval(int pid, void* interval);
long __syscall_nanosleep(void* duration, void* rem);
long __syscall_mremap(long old_addr, long old_len, long new_len, long flags);
long __syscall_setresuid(int ruid, int euid, int suid);
long __syscall_getresuid(int* ruid, int* euid, int* suid);
long __syscall_vm86(void* v86);
long __syscall_query_module(const char* name, int which, void* buf, long bufsize, long* ret);
long __syscall_poll(void* fds, long nfds, int timeout);
long __syscall_nfsservctl(void);
long __syscall_setresgid(int rgid, int egid, int sgid);
long __syscall_getresgid(int* rgid, int* egid, int* sgid);
long __syscall_prctl(int option, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5);
long __syscall_rt_sigreturn(void);
long __syscall_rt_sigaction(long sig, void* actptr, void* oldactptr, long sigsetsize);
long __syscall_rt_sigprocmask(long how, void* set, void* oldset, long sigsetsize);
long __syscall_rt_sigpending(void* set, long sigsetsize);
long __syscall_rt_sigtimedwait(const void* uthese, void* uinfo, const void* uts, long sigsetsize);
long __syscall_rt_sigqueueinfo(int pid, int sig, void* uinfo);
long __syscall_rt_sigsuspend(void* unewset, long sigsetsize);
int __syscall_pread64(int fd, void* buf, int count, int low, int high);
long __syscall_pwrite64(int fd, void* buf, long count, long offsetLow, long offsetHigh);
long __syscall_chown(const char* filename, int user, int group);
long __syscall_getcwd(char* a1, long a2);
long __syscall_capget(void* header, void* dataptr);
long __syscall_capset(void* header, const void* data);
long __syscall_sigaltstack(void* ss, void* oldss);
long __syscall_sendfile(int out_fd, int in_fd, long* offset, long count);
long __syscall_getpmsg(void);
long __syscall_putpmsg(void);
long __syscall_vfork(void);
long __syscall_ugetrlimit(long a1, unsigned long* a2);
long __syscall_mmap2(long a1, long a2, long a3, long a4, long a5, long a6);
long __syscall_truncate64(const char* path, long low, long high);
long __syscall_ftruncate64(long a1, long a2, long a3);
long __syscall_stat64(const char* pathname, void* statBuf);
long __syscall_lstat64(const char* pathname, void* statBuf);
long __syscall_fstat64(int fd, void* statBuf);
long __syscall_lchown32(const char* filename, int user, int group);
long __syscall_getuid32(void);
long __syscall_getgid32(void);
long __syscall_geteuid32(void);
long __syscall_getegid32(void);
long __syscall_setreuid32(int ruid, int euid);
long __syscall_setregid32(int rgid, int egid);
long __syscall_getgroups32(int gidsetsize, void* grouplist);
long __syscall_setgroups32(int gidsetsize, void* grouplist);
long __syscall_fchown32(unsigned int fd, int user, int group);
long __syscall_setresuid32(int ruid, int euid, int suid);
long __syscall_getresuid32(int* ruid, int* euid, int* suid);
long __syscall_setresgid32(int rgid, int egid, int sgid);
long __syscall_getresgid32(int* rgid, int* egid, int* sgid);
long __syscall_chown32(const char* filename, int user, int group);
long __syscall_setuid32(int uid);
long __syscall_setgid32(int gid);
long __syscall_setfsuid32(int uid);
long __syscall_setfsgid32(int gid);
long __syscall_pivot_root(const char* new_root, const char* put_old);
long __syscall_mincore(unsigned long start, long len, unsigned char* vec);
long __syscall_madvise(void* addr, long length, long advice);
long __syscall_getdents64(int fd, void* buf, long len);
long __syscall_fcntl64(int fd, int op, ...);
long __syscall_gettid(void);
long __syscall_readahead(int fd, long offsetLow, long offsetHigh, long count);
long __syscall_setxattr(const char* path, const char* name, const void* value, long size, int flags);
long __syscall_lsetxattr(const char* path, const char* name, const void* value, long size, int flags);
long __syscall_fsetxattr(int fd, const char* name, const void* value, long size, int flags);
long __syscall_getxattr(const char* path, const char* name, void* value, long size);
long __syscall_lgetxattr(const char* path, const char* name, void* value, long size);
long __syscall_fgetxattr(int fd, const char* name, void* value, long size);
long __syscall_listxattr(const char* path, char* list, long size);
long __syscall_llistxattr(const char* path, char* list, long size);
long __syscall_flistxattr(int fd, char* list, long size);
long __syscall_removexattr(const char* path, const char* name);
long __syscall_lremovexattr(const char* path, const char* name);
long __syscall_fremovexattr(int fd, const char* name);
long __syscall_tkill(int pid, int sig);
long __syscall_sendfile64(int out_fd, int in_fd, long* offset, long count);
long __syscall_futex(int* uaddr, int futex_op, ...);
long __syscall_sched_setaffinity(int pid, unsigned int len, unsigned long* user_mask_ptr);
long __syscall_sched_getaffinity(long pid, int cpusetsize, unsigned long* mask);
long __syscall_set_thread_area(unsigned long tp);
long __syscall_get_thread_area(void* u_info);
long __syscall_io_setup(unsigned nr_reqs, void* ctx);
long __syscall_io_destroy(long ctx);
long __syscall_io_getevents(long ctx_id, long min_nr, long nr, void* events, void* timeout);
long __syscall_io_submit(long ctx, long nr, void** iocbpp);
long __syscall_io_cancel(long ctx_id, void* iocb, void* result);
long __syscall_fadvise64(int fd, long offset, long len, int advice);
long __syscall_exit_group(int error_code);
long __syscall_lookup_dcookie(unsigned long cookie64, char* buf, long len);
long __syscall_epoll_create(int size);
long __syscall_epoll_ctl(int efd, int op, int fd, void* event);
long __syscall_epoll_wait(int epfd, void* events, int maxevents, int timeout);
long __syscall_remap_file_pages(unsigned long start, unsigned long size, unsigned long prot, unsigned long pgoff, unsigned long flags);
long __syscall_set_tid_address(int *tidptr);
long __syscall_timer_create(int which_clock, void* timer_event_spec, void* created_timer_id);
long __syscall_timer_settime32(int timer_id, int flags, const void* new_setting, void* old_setting);
long __syscall_timer_gettime32(int timer_id, void* setting);
long __syscall_timer_getoverrun(int timer_id);
long __syscall_timer_delete(int timer_id);
long __syscall_clock_settime32(int clk_id, const struct timespec* tp);
long __syscall_clock_gettime32(int clk_id, struct timespec* res);
long __syscall_clock_getres_time32(int clk_id, struct timespec* res);
long __syscall_clock_nanosleep_time32(int clock_id, int flags, const struct timespec* t, struct timespec* remain);
long __syscall_statfs64(const char* path, long sz, void* buf);
long __syscall_fstatfs64(unsigned int fd, long sz, void* buf);
long __syscall_tgkill(int tgid, int pid, int sig);
long __syscall_utimes(char* filename, void* utimes);
long __syscall_fadvise64_64(int fd, long offset_low, long offset_high, long len_low, long len_high, int advice);
long __syscall_vserver(void);
long __syscall_mbind(unsigned long start, unsigned long len, unsigned long mode, const unsigned long* nmask, unsigned long maxnode, unsigned flags);
long __syscall_get_mempolicy(int* policy, unsigned long* nmask, unsigned long maxnode, unsigned long addr, unsigned long flags);
long __syscall_set_mempolicy(int mode, const unsigned long* nmask, unsigned long maxnode);
long __syscall_mq_open(const char* name, int oflag, int mode, void* attr);
long __syscall_mq_unlink(const char* name);
long __syscall_mq_timedsend(int mqdes, const char* msg_ptr, long msg_len, unsigned int msg_prio, const void* abs_timeout);
long __syscall_mq_timedreceive(int mqdes, char* msg_ptr, long msg_len, unsigned int* msg_prio, const void* abs_timeout);
long __syscall_mq_notify(int mqdes, const void* notification);
long __syscall_mq_getsetattr(int mqdes, const void* newattr, void* oldattr);
long __syscall_kexec_load(unsigned long entry, unsigned long nr_segments, void* segments, unsigned long flags);
long __syscall_waitid(int which, int pid, void* infop, int options, void* ru);
long __syscall_sys_setaltroot(void);
long __syscall_add_key(const char* type, const char* description, const void* payload, long plen, int destringid);
long __syscall_request_key(const char* type, const char* description, const char* callout_info, int destringid);
long __syscall_keyctl(int cmd, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5);
long __syscall_ioprio_set(int which, int who, int ioprio);
long __syscall_ioprio_get(int which, int who);
long __syscall_inotify_init(void);
long __syscall_inotify_add_watch(int fd, const char *pathname, int mask);
long __syscall_inotify_rm_watch(int fd, int wd);
long __syscall_migrate_pages(int pid, unsigned long maxnode, const unsigned long* old_nodes, const unsigned long* new_nodes);
long __syscall_openat(int dirfd, const char *pathname, int flags, ...);
long __syscall_mkdirat(int dirfd, const char* pathname, int mode);
long __syscall_mknodat(int dirfd, const char* pathname, int mode, unsigned dev);
long __syscall_fchownat(int dirfd, const char* pathname, int uid, int gid, int flags);
long __syscall_futimesat(int dirfd, const char* pathname, void* utimes);
long __syscall_fstatat64(int dirfd, const char* pathname, void* statbuf, int flags);
long __syscall_unlinkat(int dirfd, const char* pathname, int flags);
long __syscall_renameat(int olddirfd, const char* oldpath, int newdirfd, const char* newpath);
long __syscall_linkat(int olddirfd, const char* oldpath, int newdirfd, const char* newpath, int flags);
long __syscall_symlinkat(const char* target, int newdirfd, const char* linkpath);
long __syscall_readlinkat(int dirfd, const char* pathname, char* buf, int bufsiz);
long __syscall_fchmodat(int dirfd, const char* pathname, int mode);
long __syscall_faccessat(int dirfd, const char* pathname, int mode);
long __syscall_pselect6(int nfds, void* readfds, void* writefds, void* exceptfds, void* timeout, void* sigmask);
long __syscall_ppoll(void* fds, long nfds, void* timeout, const void* sigmask, long sigsetsize);
long __syscall_unshare(unsigned long unshare_flags);
long __syscall_set_robust_list(void* head, long len);
long __syscall_get_robust_list(int pid, void** head_ptr, long* len_ptr);
long __syscall_splice(int fd_in, long* off_in, int fd_out, long* off_out, long len, unsigned int flags);
long __syscall_sync_file_range(int fd, long offsetLow, long offsetHigh, long nbytesLow, long nbytesHigh, unsigned int flags);
long __syscall_tee(int fdin, int fdout, long len, unsigned int flags);
long __syscall_vmsplice(int fd, const void* iov, unsigned long nr_segs, unsigned int flags);
long __syscall_move_pages(int pid, unsigned long nr_pages, const void** pages, const int* nodes, int* status, int flags);
long __syscall_getcpu(unsigned* cpu, unsigned* node, void* cache);
int __syscall_epoll_pwait(int fd, struct epoll_event* events, int maxEvents, int timeout, const void* sigMask, int maxSig);
long __syscall_utimensat(int dirfd, const char* pathname, const void* times, int flags);
long __syscall_signalfd(int ufd, void* user_mask, long sizemask);
long __syscall_timerfd_create(int clockid, int flags);
long __syscall_eventfd(unsigned int initval);
long __syscall_fallocate(int fd, int mode, long offsetLow, long offsetHigh, long lenLow, long lenHigh);
long __syscall_timerfd_settime32(int ufd, int flags, const void* utmr, void* otmr);
long __syscall_timerfd_gettime32(int ufd, void* otmr);
long __syscall_signalfd4(int ufd, void* user_mask, long sizemask, int flags);
long __syscall_eventfd2(unsigned int initval, int flags);
long __syscall_epoll_create1(int flags);
long __syscall_dup3(int oldfd, int newfd, int flags);
long __syscall_pipe2(void* fds, int flags);
long __syscall_inotify_init1(int flags);
long __syscall_preadv(int fd, const void* vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h);
long __syscall_pwritev(int fd, const void* vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h);
long __syscall_rt_tgsigqueueinfo(int tgid, int pid, int sig, void* uinfo);
long __syscall_perf_event_open(void* attr_uptr, int pid, int cpu, int group_fd, unsigned long flags);
long __syscall_recvmmsg(int fd, void* msg, unsigned int vlen, unsigned flags, void* timeout);
long __syscall_fanotify_init(unsigned int flags, unsigned int event_f_flags);
long __syscall_fanotify_mark(int fanotify_fd, unsigned int flags, unsigned long maskLow, unsigned long maskHigh, int fd, const char* pathname);
long __syscall_prlimit64(unsigned int pid, int resource, void* newptr, void* oldptr);
long __syscall_name_to_handle_at(int dfd, const char* name, void* handle, int* mnt_id, int flag);
long __syscall_open_by_handle_at(int mountdirfd, void* handle, int flags);
long __syscall_clock_adjtime(int which_clock, void* tx);
long __syscall_syncfs(int fd);
long __syscall_sendmmsg(int fd, void* msg, unsigned int vlen, unsigned flags);
long __syscall_setns(int fd, int nstype);
long __syscall_process_vm_readv(int pid, const void* lvec, unsigned long liovcnt, const void* rvec, unsigned long riovcnt, unsigned long flags);
long __syscall_process_vm_writev(int pid, const void* lvec, unsigned long liovcnt, const void* rvec, unsigned long riovcnt, unsigned long flags);
long __syscall_kcmp(int pid1, int pid2, int type, unsigned long idx1, unsigned long idx2);
long __syscall_finit_module(int fd, const char* uargs, int flags);
long __syscall_sched_setattr(int pid, void* attr, unsigned int flags);
long __syscall_sched_getattr(int pid, void* attr, unsigned int size, unsigned int flags);
long __syscall_renameat2(int olddirfd, const char* oldpath, int newdirfd, const char* newpath, unsigned int flags);
long __syscall_seccomp(unsigned int op, unsigned int flags, void* uargs);
long __syscall_getrandom(void* buf, long buflen, unsigned int flags);
long __syscall_memfd_create(const char* uname, unsigned int flags);
long __syscall_bpf(int cmd, void* attr, unsigned int size);
long __syscall_execveat(int dfd, const char* filename, const char* const* argv, const char* const* envp, int flags);
long __syscall_socket(int domain, int type, int protocol, int, int, int);
long __syscall_socketpair(long domain, long type, long protocol, int* sv, int, int);
int __syscall_bind(int fd, const struct sockaddr* addr, int addrlen, int, int, int);
int __syscall_connect(int fd, const struct sockaddr* addr, int addrlen, int, int, int);
long __syscall_listen(int fd, int backlog, int, int, int, int);
int __syscall_accept4(int fd, struct sockaddr* addr, int* addrlen, int, int, int);
long __syscall_getsockopt(int fd, int level, int optname, void* optval, int* optlen, int);
long __syscall_setsockopt(int fd, int level, int optname, void* optval, int optlen, int);
long __syscall_getsockname(int fd, struct sockaddr* addr, int addrlen, int, int, int);
long __syscall_getpeername(int fd, struct sockaddr* addr, int* addrlen, int, int, int);
long __syscall_sendto(int fd, void* buf, int count, int flags, struct sockaddr* addr, int addrlen);
long __syscall_sendmsg(int fd, struct msghdr* msg, unsigned flags, int, int, int);
long __syscall_recvfrom(int fd, void* buf, int count, int flags, struct sockaddr* addr, int* addrlen);
int __syscall_recvmsg(int fd, struct msghdr* msg, int flags, int, int, int);
long __syscall_shutdown(int fd, int how, int, int, int, int);
long __syscall_userfaultfd(int flags);
long __syscall_membarrier(int cmd, unsigned int flags);
long __syscall_mlock2(unsigned long start, long len, int flags);
long __syscall_copy_file_range(int fd_in, long* off_in, int fd_out, long* off_out, long len, unsigned int flags);
long __syscall_preadv2(int fd, const void* vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h, int flags);
long __syscall_pwritev2(int fd, const void* vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h, int flags);
long __syscall_pkey_mprotect(unsigned long start, long len, unsigned long prot, int pkey);
long __syscall_pkey_alloc(unsigned long flags, unsigned long init_val);
long __syscall_pkey_free(int pkey);
long __syscall_statx(int dfd, const char* path, unsigned flags, unsigned mask, void* buffer);
long __syscall_arch_prctl(int option, unsigned long arg2);
long __syscall_io_pgetevents(long ctx_id, long min_nr, long nr, void* events, void* timeout, const void* sig);
long __syscall_rseq(void* rseq, unsigned int rseq_len, int flags, unsigned int sig);
long __syscall_semget(int key, int nsems, int semflg);
long __syscall_semctl(int semid, int semnum, int cmd, unsigned long arg);
long __syscall_shmget(int key, long size, int flag);
long __syscall_shmctl(int shmid, int cmd, void* buf);
long __syscall_shmat(int shmid, char* shmaddr, int shmflg);
long __syscall_shmdt(char* shmaddr);
long __syscall_msgget(int key, int msgflg);
long __syscall_msgsnd(int msqid, void* msgp, long msgsz, int msgflg);
long __syscall_msgrcv(int msqid, void* msgp, long msgsz, long msgtyp, int msgflg);
long __syscall_msgctl(int msqid, int cmd, void* buf);
long __syscall_clock_gettime64(int clk_id, struct timespec* res);
long __syscall_clock_settime64(int clk_id, const struct timespec* tp);
long __syscall_clock_adjtime64(int which_clock, void* tx);
long __syscall_clock_getres_time64(int clk_id, struct timespec* res);
long __syscall_clock_nanosleep_time64(int clock_id, int flags, const struct timespec* t, struct timespec* remain);
long __syscall_timer_gettime64(int timer_id, void* setting);
long __syscall_timer_settime64(int timer_id, int flags, const void* new_setting, void* old_setting);
long __syscall_timerfd_gettime64(int ufd, void* otmr);
long __syscall_timerfd_settime64(int ufd, int flags, const void* utmr, void* otmr);
long __syscall_utimensat_time64(int dirfd, const char* pathname, const void* times, int flags);
long __syscall_pselect6_time64(int nfds, void* readfds, void* writefds, void* exceptfds, void* timeout, void* sigmask);
long __syscall_ppoll_time64(void* fds, long nfds, void* timeout, const void* sigmask, long sigsetsize);
long __syscall_io_pgetevents_time64(long ctx_id, long min_nr, long nr, void* events, void* timeout, const void* sig);
long __syscall_recvmmsg_time64(int fd, void* msg, unsigned int vlen, unsigned flags, void* timeout);
long __syscall_mq_timedsend_time64(int mqdes, const char* msg_ptr, long msg_len, unsigned int msg_prio, const void* abs_timeout);
long __syscall_mq_timedreceive_time64(int mqdes, char* msg_ptr, long msg_len, unsigned int* msg_prio, const void* abs_timeout);
long __syscall_semtimedop_time64(int semid, void* sops, unsigned nsops, const void* timeout);
long __syscall_rt_sigtimedwait_time64(const void* uthese, void* uinfo, const void* uts, long sigsetsize);
long __syscall_sched_rr_get_interval_time64(int pid, void* interval);
long __syscall_pidfd_send_signal(int pidfd, int sig, void* info, unsigned int flags);
long __syscall_io_uring_setup(unsigned int entries, void* params);
long __syscall_io_uring_enter(unsigned int fd, unsigned int to_submit, unsigned int min_complete, unsigned int flags, const void* sig, long sigsz);
long __syscall_io_uring_register(unsigned int fd, unsigned int opcode, void* arg, unsigned int nr_args);
long __syscall_open_tree(int dfd, const char* pathname, unsigned flags);
long __syscall_move_mount(int from_dfd, const char* from_pathname, int to_dfd, const char* to_pathname, unsigned int flags);
long __syscall_fsopen(const char* fs_name, unsigned int flags);
long __syscall_fsconfig(int fd, unsigned int cmd, const char* key, const void* value, int aux);
long __syscall_fsmount(int fd, unsigned int flags, unsigned int ms_flags);
long __syscall_fspick(int dfd, const char* pathname, unsigned int flags);
long __syscall_pidfd_open(int pid, unsigned int flags);
long __syscall_clone3(void* uargs, long size);
long __syscall_close_range(unsigned int fd, unsigned int max_fd, unsigned int flags);
long __syscall_openat2(int dfd, const char* pathname, void* how, long size);
long __syscall_pidfd_getfd(int pidfd, int targetfd, unsigned int flags);
long __syscall_faccessat2(int dirfd, const char *pathname, int mode, int flags);
long __syscall_process_madvise(int pidfd, const void* vec, long vlen, int behavior, unsigned int flags);


//#define VDSO_USEFUL
//#define VDSO_CGT32_SYM "__vdso_clock_gettime"
//#define VDSO_CGT32_VER "LINUX_2.6"
//#define VDSO_CGT_SYM "__vdso_clock_gettime64"
//#define VDSO_CGT_VER "LINUX_2.6"
