#define __SYSCALL_LL_E(x) \
((union { long long ll; long l[2]; }){ .ll = x }).l[0], \
((union { long long ll; long l[2]; }){ .ll = x }).l[1]
#define __SYSCALL_LL_O(x) __SYSCALL_LL_E((x))

#define __SYSCALL_DIRECT 1

#ifndef SYSCALL_DEF
#define __SYSCALL_DEF_DECL
#if defined(__wasm__) && !defined(__CHEERP__)
#define __SYSCALL_ATTR(name) __attribute__((import_module("i"), import_name("__syscall_" #name)))
#else
#define __SYSCALL_ATTR(name)
#endif
#define SYSCALL_DEF(name, ...) long __SYSCALL_ATTR(name) __syscall_ ## name(__VA_ARGS__)
#endif

struct iovec;
struct rlimit;
struct sched_param;
struct timespec;
struct sockaddr;
struct msghdr;
struct epoll_event;
struct rusage;
struct iocb;

SYSCALL_DEF(restart_syscall);
SYSCALL_DEF(exit, int error_code);
SYSCALL_DEF(fork);
SYSCALL_DEF(read, int fd, void* buf, int count);
SYSCALL_DEF(write, int fd, void* buf, int count);
SYSCALL_DEF(open, const char* pathname, int flags, ...);
SYSCALL_DEF(close, int fd);
SYSCALL_DEF(waitpid, int pid, int* wstatus, int options);
SYSCALL_DEF(creat, const char* pathname, int mode);
SYSCALL_DEF(link, const char *oldpath, const char *newpath);
SYSCALL_DEF(unlink, const char *pathname);
SYSCALL_DEF(execve, const char* path, char* const argv[], char* const envp[]);
SYSCALL_DEF(chdir, const char* filename);
SYSCALL_DEF(time, long* tloc);
SYSCALL_DEF(mknod, const char* filename, int mode, unsigned dev);
SYSCALL_DEF(chmod, const char *pathname, int mode);
SYSCALL_DEF(lchown, const char* filename, int user, int group);
SYSCALL_DEF(break);
SYSCALL_DEF(oldstat, const char* filename, void* statbuf);
SYSCALL_DEF(lseek, int fd, long offset, unsigned int whence);
SYSCALL_DEF(getpid);
SYSCALL_DEF(mount, char* dev_name, char* dir_name, char* type, unsigned long flags, void* data);
SYSCALL_DEF(umount, char* name);
SYSCALL_DEF(setuid, int uid);
SYSCALL_DEF(getuid);
SYSCALL_DEF(stime, long* tptr);
SYSCALL_DEF(ptrace, long request, long pid, unsigned long addr, unsigned long data, unsigned long addr2);
SYSCALL_DEF(alarm, unsigned int seconds);
SYSCALL_DEF(oldfstat, int fd, void* statbuf);
SYSCALL_DEF(pause);
SYSCALL_DEF(utime, char* filename, void* times);
SYSCALL_DEF(stty);
SYSCALL_DEF(gtty);
SYSCALL_DEF(access, const char *pathname, int mode);
SYSCALL_DEF(nice, int increment);
SYSCALL_DEF(ftime);
SYSCALL_DEF(sync);
SYSCALL_DEF(kill, int pid, int sig);
SYSCALL_DEF(rename, const char *oldpath, const char *newpath);
SYSCALL_DEF(mkdir, const char *pathname, int mode);
SYSCALL_DEF(rmdir, const char *path);
SYSCALL_DEF(dup, unsigned int fildes);
SYSCALL_DEF(pipe, int* fildes);
SYSCALL_DEF(times, void* tbuf);
SYSCALL_DEF(prof);
SYSCALL_DEF(brk, void* newaddr);
SYSCALL_DEF(setgid, int gid);
SYSCALL_DEF(getgid);
SYSCALL_DEF(signal, int sig, void* handler);
SYSCALL_DEF(geteuid);
SYSCALL_DEF(getegid);
SYSCALL_DEF(acct, const char* name);
SYSCALL_DEF(umount2, char* name, int flags);
SYSCALL_DEF(lock);
SYSCALL_DEF(ioctl, long fd, long req, void* arg);
SYSCALL_DEF(fcntl, unsigned int fd, unsigned int cmd, unsigned long arg);
SYSCALL_DEF(mpx);
SYSCALL_DEF(setpgid, int pid, int pgid);
SYSCALL_DEF(ulimit);
SYSCALL_DEF(oldolduname, void* name);
SYSCALL_DEF(umask, int mode);
SYSCALL_DEF(chroot, const char* filename);
SYSCALL_DEF(ustat, unsigned dev, void* ubuf);
SYSCALL_DEF(dup2, int oldfd, int newfd);
SYSCALL_DEF(getppid);
SYSCALL_DEF(getpgrp);
SYSCALL_DEF(setsid);
SYSCALL_DEF(sigaction, int sig, const void* act, void* oldact);
SYSCALL_DEF(sgetmask);
SYSCALL_DEF(ssetmask, long newmask);
SYSCALL_DEF(setreuid, int ruid, int euid);
SYSCALL_DEF(setregid, int rgid, int egid);
SYSCALL_DEF(sigsuspend, const void* mask);
SYSCALL_DEF(sigpending, void* set);
SYSCALL_DEF(sethostname, char* name, int len);
SYSCALL_DEF(setrlimit, unsigned int resource, struct rlimit* rlim);
SYSCALL_DEF(getrlimit, unsigned int resource, struct rlimit* rlim);
SYSCALL_DEF(getrusage, int resource, void* rlim);
SYSCALL_DEF(gettimeofday_time32, void* tv, void* tz);
SYSCALL_DEF(settimeofday_time32, void* tv, void* tz);
SYSCALL_DEF(getgroups, int gidsetsize, void* grouplist);
SYSCALL_DEF(setgroups, int gidsetsize, void* grouplist);
SYSCALL_DEF(select, int n, void* inp, void* outp, void* exp, void* tvp);
SYSCALL_DEF(symlink, const char *target, const char *linkpath);
SYSCALL_DEF(oldlstat, const char* filename, void* statbuf);
SYSCALL_DEF(readlink, const char* pathname, char* buf, long bufsize);
SYSCALL_DEF(uselib, const char* library);
SYSCALL_DEF(swapon, const char* specialfile, int swap_flags);
SYSCALL_DEF(reboot, int magic1, int magic2, unsigned int cmd);
SYSCALL_DEF(readdir, unsigned int fd, void* dirent, unsigned int count);
SYSCALL_DEF(mmap, unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags, unsigned long fd, unsigned long offset);
SYSCALL_DEF(munmap, long a1, long length);
SYSCALL_DEF(truncate, const char* path, long length);
SYSCALL_DEF(ftruncate, unsigned int fd, unsigned long length);
SYSCALL_DEF(fchmod, unsigned int fd, int mode);
SYSCALL_DEF(fchown, unsigned int fd, int user, int group);
SYSCALL_DEF(getpriority, int which, int who);
SYSCALL_DEF(setpriority, int which, int who, int niceval);
SYSCALL_DEF(profil);
SYSCALL_DEF(statfs, const char* path, void* buf);
SYSCALL_DEF(fstatfs, unsigned int fd, void* buf);
SYSCALL_DEF(ioperm, unsigned long from, unsigned long num, int on);
SYSCALL_DEF(socketcall, int call, unsigned long* args);
SYSCALL_DEF(syslog, int type, char* buf, int len);
SYSCALL_DEF(setitimer, int which, void* value, void* ovalue);
SYSCALL_DEF(getitimer, int which, void* value);
SYSCALL_DEF(stat, const char* filename, void* statbuf);
SYSCALL_DEF(lstat, const char* filename, void* statbuf);
SYSCALL_DEF(fstat, int fd, void* statbuf);
SYSCALL_DEF(olduname, void* name);
SYSCALL_DEF(iopl, unsigned int level);
SYSCALL_DEF(vhangup);
SYSCALL_DEF(idle);
SYSCALL_DEF(vm86old, void* v86);
SYSCALL_DEF(wait4, unsigned int pid, int* wstatus, int options, void* rusage);
SYSCALL_DEF(swapoff, const char* specialfile);
SYSCALL_DEF(sysinfo, void* info);
SYSCALL_DEF(ipc, long a1, ...);
SYSCALL_DEF(fsync, unsigned int fd);
SYSCALL_DEF(sigreturn);
SYSCALL_DEF(clone, unsigned long flags, unsigned long stack, int* parent_tid, unsigned long tls, int* child_tid);
SYSCALL_DEF(clone4, int (*func)(void *), void *stack, int flags, void *arg, void *ptid, void *tls, void *ctid);
SYSCALL_DEF(setdomainname, char* name, int len);
SYSCALL_DEF(uname, void* utsname);
SYSCALL_DEF(modify_ldt, int func, void* ptr, unsigned long bytecount);
SYSCALL_DEF(adjtimex, void* txc_p);
SYSCALL_DEF(mprotect, long addr, long len, int flags);
SYSCALL_DEF(sigprocmask, int how, const void* set, void* oldset);
SYSCALL_DEF(create_module, const char* name, unsigned long size);
SYSCALL_DEF(init_module, void* umod, unsigned long len, const char* uargs);
SYSCALL_DEF(delete_module, const char* name_user, unsigned int flags);
SYSCALL_DEF(get_kernel_syms, void* table);
SYSCALL_DEF(quotactl, unsigned int cmd, const char* special, int id, void* addr);
SYSCALL_DEF(getpgid, int pid);
SYSCALL_DEF(fchdir, unsigned int fd);
SYSCALL_DEF(bdflush, int func, long data);
SYSCALL_DEF(sysfs, int option, unsigned long arg1, unsigned long arg2);
SYSCALL_DEF(personality, unsigned int personality);
SYSCALL_DEF(afs_syscall);
SYSCALL_DEF(setfsuid, int uid);
SYSCALL_DEF(setfsgid, int gid);
SYSCALL_DEF(_llseek, unsigned int a1, unsigned long a2, unsigned long a3, long* a4, unsigned int a5);
SYSCALL_DEF(getdents, int fd, void* buf, long len);
SYSCALL_DEF(_newselect, long nfds, void* readfds, void* writefds, void* exceptfds, void* timeout);
SYSCALL_DEF(flock, unsigned int fd, unsigned int cmd);
SYSCALL_DEF(msync, unsigned long start, long len, int flags);
SYSCALL_DEF(readv, long fd, const struct iovec* ios, long len);
SYSCALL_DEF(writev, long fd, const struct iovec* ios, long len);
SYSCALL_DEF(getsid, int pid);
SYSCALL_DEF(fdatasync, unsigned int fd);
SYSCALL_DEF(_sysctl, void* args);
SYSCALL_DEF(mlock, unsigned long start, long len);
SYSCALL_DEF(munlock, unsigned long start, long len);
SYSCALL_DEF(mlockall, int flags);
SYSCALL_DEF(munlockall);
SYSCALL_DEF(sched_setparam, int pid, struct sched_param* param);
SYSCALL_DEF(sched_getparam, int pid, struct sched_param* param);
SYSCALL_DEF(sched_setscheduler, long pid, int policy, const struct sched_param *param);
SYSCALL_DEF(sched_getscheduler, int pid);
SYSCALL_DEF(sched_yield);
SYSCALL_DEF(sched_get_priority_max, int policy);
SYSCALL_DEF(sched_get_priority_min, int policy);
SYSCALL_DEF(sched_rr_get_interval, int pid, void* interval);
SYSCALL_DEF(nanosleep, void* duration, void* rem);
SYSCALL_DEF(mremap, long old_addr, long old_len, long new_len, long flags);
SYSCALL_DEF(setresuid, int ruid, int euid, int suid);
SYSCALL_DEF(getresuid, int* ruid, int* euid, int* suid);
SYSCALL_DEF(vm86, void* v86);
SYSCALL_DEF(query_module, const char* name, int which, void* buf, long bufsize, long* ret);
SYSCALL_DEF(poll, void* fds, long nfds, int timeout);
SYSCALL_DEF(nfsservctl);
SYSCALL_DEF(setresgid, int rgid, int egid, int sgid);
SYSCALL_DEF(getresgid, int* rgid, int* egid, int* sgid);
SYSCALL_DEF(prctl, int option, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5);
SYSCALL_DEF(rt_sigreturn);
SYSCALL_DEF(rt_sigaction, long sig, void* actptr, void* oldactptr, long sigsetsize);
SYSCALL_DEF(rt_sigprocmask, long how, void* set, void* oldset, long sigsetsize);
SYSCALL_DEF(rt_sigpending, void* set, long sigsetsize);
SYSCALL_DEF(rt_sigtimedwait, const void* uthese, void* uinfo, const void* uts, long sigsetsize);
SYSCALL_DEF(rt_sigqueueinfo, int pid, int sig, void* uinfo);
SYSCALL_DEF(rt_sigsuspend, void* unewset, long sigsetsize);
SYSCALL_DEF(pread64, int fd, void* buf, int count, int low, int high);
SYSCALL_DEF(pwrite64, int fd, void* buf, long count, long offsetLow, long offsetHigh);
SYSCALL_DEF(chown, const char* filename, int user, int group);
SYSCALL_DEF(getcwd, char* a1, long a2);
SYSCALL_DEF(capget, void* header, void* dataptr);
SYSCALL_DEF(capset, void* header, const void* data);
SYSCALL_DEF(sigaltstack, void* ss, void* oldss);
SYSCALL_DEF(sendfile, int out_fd, int in_fd, long* offset, long count);
SYSCALL_DEF(getpmsg);
SYSCALL_DEF(putpmsg);
SYSCALL_DEF(vfork);
SYSCALL_DEF(ugetrlimit, long a1, unsigned long* a2);
SYSCALL_DEF(mmap2, long a1, long a2, long a3, long a4, long a5, long a6);
SYSCALL_DEF(truncate64, const char* path, long low, long high);
SYSCALL_DEF(ftruncate64, long a1, long a2, long a3);
SYSCALL_DEF(stat64, const char* pathname, void* statBuf);
SYSCALL_DEF(lstat64, const char* pathname, void* statBuf);
SYSCALL_DEF(fstat64, int fd, void* statBuf);
SYSCALL_DEF(lchown32, const char* filename, int user, int group);
SYSCALL_DEF(getuid32);
SYSCALL_DEF(getgid32);
SYSCALL_DEF(geteuid32);
SYSCALL_DEF(getegid32);
SYSCALL_DEF(setreuid32, int ruid, int euid);
SYSCALL_DEF(setregid32, int rgid, int egid);
SYSCALL_DEF(getgroups32, int gidsetsize, void* grouplist);
SYSCALL_DEF(setgroups32, int gidsetsize, void* grouplist);
SYSCALL_DEF(fchown32, unsigned int fd, int user, int group);
SYSCALL_DEF(setresuid32, int ruid, int euid, int suid);
SYSCALL_DEF(getresuid32, int* ruid, int* euid, int* suid);
SYSCALL_DEF(setresgid32, int rgid, int egid, int sgid);
SYSCALL_DEF(getresgid32, int* rgid, int* egid, int* sgid);
SYSCALL_DEF(chown32, const char* filename, int user, int group);
SYSCALL_DEF(setuid32, int uid);
SYSCALL_DEF(setgid32, int gid);
SYSCALL_DEF(setfsuid32, int uid);
SYSCALL_DEF(setfsgid32, int gid);
SYSCALL_DEF(pivot_root, const char* new_root, const char* put_old);
SYSCALL_DEF(mincore, unsigned long start, long len, unsigned char* vec);
SYSCALL_DEF(madvise, void* addr, long length, long advice);
SYSCALL_DEF(getdents64, int fd, void* buf, long len);
SYSCALL_DEF(fcntl64, int fd, int op, ...);
SYSCALL_DEF(gettid);
SYSCALL_DEF(readahead, int fd, long offsetLow, long offsetHigh, long count);
SYSCALL_DEF(setxattr, const char* path, const char* name, const void* value, long size, int flags);
SYSCALL_DEF(lsetxattr, const char* path, const char* name, const void* value, long size, int flags);
SYSCALL_DEF(fsetxattr, int fd, const char* name, const void* value, long size, int flags);
SYSCALL_DEF(getxattr, const char* path, const char* name, void* value, long size);
SYSCALL_DEF(lgetxattr, const char* path, const char* name, void* value, long size);
SYSCALL_DEF(fgetxattr, int fd, const char* name, void* value, long size);
SYSCALL_DEF(listxattr, const char* path, char* list, long size);
SYSCALL_DEF(llistxattr, const char* path, char* list, long size);
SYSCALL_DEF(flistxattr, int fd, char* list, long size);
SYSCALL_DEF(removexattr, const char* path, const char* name);
SYSCALL_DEF(lremovexattr, const char* path, const char* name);
SYSCALL_DEF(fremovexattr, int fd, const char* name);
SYSCALL_DEF(tkill, int pid, int sig);
SYSCALL_DEF(sendfile64, int out_fd, int in_fd, long* offset, long count);
SYSCALL_DEF(futex, int* uaddr, int futex_op, ...);
SYSCALL_DEF(sched_setaffinity, int pid, unsigned int len, unsigned long* user_mask_ptr);
SYSCALL_DEF(sched_getaffinity, long pid, int cpusetsize, unsigned long* mask);
SYSCALL_DEF(set_thread_area, unsigned long tp);
SYSCALL_DEF(get_thread_area, void* u_info);
SYSCALL_DEF(io_setup, unsigned nr_reqs, void* ctx);
SYSCALL_DEF(io_destroy, long ctx);
SYSCALL_DEF(io_getevents, long ctx_id, long min_nr, long nr, void* events, void* timeout);
SYSCALL_DEF(io_submit, long ctx, long nr, void** iocbpp);
SYSCALL_DEF(io_cancel, long ctx_id, void* iocb, void* result);
SYSCALL_DEF(fadvise64, int fd, long offset, long len, int advice);
SYSCALL_DEF(exit_group, int error_code);
SYSCALL_DEF(lookup_dcookie, unsigned long cookie64, char* buf, long len);
SYSCALL_DEF(epoll_create, int size);
SYSCALL_DEF(epoll_ctl, int efd, int op, int fd, void* event);
SYSCALL_DEF(epoll_wait, int epfd, void* events, int maxevents, int timeout);
SYSCALL_DEF(remap_file_pages, unsigned long start, unsigned long size, unsigned long prot, unsigned long pgoff, unsigned long flags);
SYSCALL_DEF(set_tid_address, int *tidptr);
SYSCALL_DEF(timer_create, int which_clock, void* timer_event_spec, void* created_timer_id);
SYSCALL_DEF(timer_settime32, int timer_id, int flags, const void* new_setting, void* old_setting);
SYSCALL_DEF(timer_gettime32, int timer_id, void* setting);
SYSCALL_DEF(timer_getoverrun, int timer_id);
SYSCALL_DEF(timer_delete, int timer_id);
SYSCALL_DEF(clock_settime32, int clk_id, const struct timespec* tp);
SYSCALL_DEF(clock_gettime32, int clk_id, struct timespec* res);
SYSCALL_DEF(clock_getres_time32, int clk_id, struct timespec* res);
SYSCALL_DEF(clock_nanosleep_time32, int clock_id, int flags, const struct timespec* t, struct timespec* remain);
SYSCALL_DEF(statfs64, const char* path, long sz, void* buf);
SYSCALL_DEF(fstatfs64, unsigned int fd, long sz, void* buf);
SYSCALL_DEF(tgkill, int tgid, int pid, int sig);
SYSCALL_DEF(utimes, char* filename, void* utimes);
SYSCALL_DEF(fadvise64_64, int fd, long offset_low, long offset_high, long len_low, long len_high, int advice);
SYSCALL_DEF(vserver);
SYSCALL_DEF(mbind, unsigned long start, unsigned long len, unsigned long mode, const unsigned long* nmask, unsigned long maxnode, unsigned flags);
SYSCALL_DEF(get_mempolicy, int* policy, unsigned long* nmask, unsigned long maxnode, unsigned long addr, unsigned long flags);
SYSCALL_DEF(set_mempolicy, int mode, const unsigned long* nmask, unsigned long maxnode);
SYSCALL_DEF(mq_open, const char* name, int oflag, int mode, void* attr);
SYSCALL_DEF(mq_unlink, const char* name);
SYSCALL_DEF(mq_timedsend, int mqdes, const char* msg_ptr, long msg_len, unsigned int msg_prio, const void* abs_timeout);
SYSCALL_DEF(mq_timedreceive, int mqdes, char* msg_ptr, long msg_len, unsigned int* msg_prio, const void* abs_timeout);
SYSCALL_DEF(mq_notify, int mqdes, const void* notification);
SYSCALL_DEF(mq_getsetattr, int mqdes, const void* newattr, void* oldattr);
SYSCALL_DEF(kexec_load, unsigned long entry, unsigned long nr_segments, void* segments, unsigned long flags);
SYSCALL_DEF(waitid, int which, int pid, void* infop, int options, void* ru);
SYSCALL_DEF(sys_setaltroot);
SYSCALL_DEF(add_key, const char* type, const char* description, const void* payload, long plen, int destringid);
SYSCALL_DEF(request_key, const char* type, const char* description, const char* callout_info, int destringid);
SYSCALL_DEF(keyctl, int cmd, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5);
SYSCALL_DEF(ioprio_set, int which, int who, int ioprio);
SYSCALL_DEF(ioprio_get, int which, int who);
SYSCALL_DEF(inotify_init);
SYSCALL_DEF(inotify_add_watch, int fd, const char *pathname, int mask);
SYSCALL_DEF(inotify_rm_watch, int fd, int wd);
SYSCALL_DEF(migrate_pages, int pid, unsigned long maxnode, const unsigned long* old_nodes, const unsigned long* new_nodes);
SYSCALL_DEF(openat, int dirfd, const char *pathname, int flags, ...);
SYSCALL_DEF(mkdirat, int dirfd, const char* pathname, int mode);
SYSCALL_DEF(mknodat, int dirfd, const char* pathname, int mode, unsigned dev);
SYSCALL_DEF(fchownat, int dirfd, const char* pathname, int uid, int gid, int flags);
SYSCALL_DEF(futimesat, int dirfd, const char* pathname, void* utimes);
SYSCALL_DEF(fstatat64, int dirfd, const char* pathname, void* statbuf, int flags);
SYSCALL_DEF(unlinkat, int dirfd, const char* pathname, int flags);
SYSCALL_DEF(renameat, int olddirfd, const char* oldpath, int newdirfd, const char* newpath);
SYSCALL_DEF(linkat, int olddirfd, const char* oldpath, int newdirfd, const char* newpath, int flags);
SYSCALL_DEF(symlinkat, const char* target, int newdirfd, const char* linkpath);
SYSCALL_DEF(readlinkat, int dirfd, const char* pathname, char* buf, int bufsiz);
SYSCALL_DEF(fchmodat, int dirfd, const char* pathname, int mode);
SYSCALL_DEF(faccessat, int dirfd, const char* pathname, int mode);
SYSCALL_DEF(pselect6, int nfds, void* readfds, void* writefds, void* exceptfds, void* timeout, void* sigmask);
SYSCALL_DEF(ppoll, void* fds, long nfds, void* timeout, const void* sigmask, long sigsetsize);
SYSCALL_DEF(unshare, unsigned long unshare_flags);
SYSCALL_DEF(set_robust_list, void* head, long len);
SYSCALL_DEF(get_robust_list, int pid, void** head_ptr, long* len_ptr);
SYSCALL_DEF(splice, int fd_in, long* off_in, int fd_out, long* off_out, long len, unsigned int flags);
SYSCALL_DEF(sync_file_range, int fd, long offsetLow, long offsetHigh, long nbytesLow, long nbytesHigh, unsigned int flags);
SYSCALL_DEF(tee, int fdin, int fdout, long len, unsigned int flags);
SYSCALL_DEF(vmsplice, int fd, const void* iov, unsigned long nr_segs, unsigned int flags);
SYSCALL_DEF(move_pages, int pid, unsigned long nr_pages, const void** pages, const int* nodes, int* status, int flags);
SYSCALL_DEF(getcpu, unsigned* cpu, unsigned* node, void* cache);
SYSCALL_DEF(epoll_pwait, int fd, struct epoll_event* events, int maxEvents, int timeout, const void* sigMask, int maxSig);
SYSCALL_DEF(utimensat, int dirfd, const char* pathname, const void* times, int flags);
SYSCALL_DEF(signalfd, int ufd, void* user_mask, long sizemask);
SYSCALL_DEF(timerfd_create, int clockid, int flags);
SYSCALL_DEF(eventfd, unsigned int initval);
SYSCALL_DEF(fallocate, int fd, int mode, long offsetLow, long offsetHigh, long lenLow, long lenHigh);
SYSCALL_DEF(timerfd_settime32, int ufd, int flags, const void* utmr, void* otmr);
SYSCALL_DEF(timerfd_gettime32, int ufd, void* otmr);
SYSCALL_DEF(signalfd4, int ufd, void* user_mask, long sizemask, int flags);
SYSCALL_DEF(eventfd2, unsigned int initval, int flags);
SYSCALL_DEF(epoll_create1, int flags);
SYSCALL_DEF(dup3, int oldfd, int newfd, int flags);
SYSCALL_DEF(pipe2, void* fds, int flags);
SYSCALL_DEF(inotify_init1, int flags);
SYSCALL_DEF(preadv, int fd, const void* vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h);
SYSCALL_DEF(pwritev, int fd, const void* vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h);
SYSCALL_DEF(rt_tgsigqueueinfo, int tgid, int pid, int sig, void* uinfo);
SYSCALL_DEF(perf_event_open, void* attr_uptr, int pid, int cpu, int group_fd, unsigned long flags);
SYSCALL_DEF(recvmmsg, int fd, void* msg, unsigned int vlen, unsigned flags, void* timeout);
SYSCALL_DEF(fanotify_init, unsigned int flags, unsigned int event_f_flags);
SYSCALL_DEF(fanotify_mark, int fanotify_fd, unsigned int flags, unsigned long maskLow, unsigned long maskHigh, int fd, const char* pathname);
SYSCALL_DEF(prlimit64, unsigned int pid, int resource, void* newptr, void* oldptr);
SYSCALL_DEF(name_to_handle_at, int dfd, const char* name, void* handle, int* mnt_id, int flag);
SYSCALL_DEF(open_by_handle_at, int mountdirfd, void* handle, int flags);
SYSCALL_DEF(clock_adjtime, int which_clock, void* tx);
SYSCALL_DEF(syncfs, int fd);
SYSCALL_DEF(sendmmsg, int fd, void* msg, unsigned int vlen, unsigned flags);
SYSCALL_DEF(setns, int fd, int nstype);
SYSCALL_DEF(process_vm_readv, int pid, const void* lvec, unsigned long liovcnt, const void* rvec, unsigned long riovcnt, unsigned long flags);
SYSCALL_DEF(process_vm_writev, int pid, const void* lvec, unsigned long liovcnt, const void* rvec, unsigned long riovcnt, unsigned long flags);
SYSCALL_DEF(kcmp, int pid1, int pid2, int type, unsigned long idx1, unsigned long idx2);
SYSCALL_DEF(finit_module, int fd, const char* uargs, int flags);
SYSCALL_DEF(sched_setattr, int pid, void* attr, unsigned int flags);
SYSCALL_DEF(sched_getattr, int pid, void* attr, unsigned int size, unsigned int flags);
SYSCALL_DEF(renameat2, int olddirfd, const char* oldpath, int newdirfd, const char* newpath, unsigned int flags);
SYSCALL_DEF(seccomp, unsigned int op, unsigned int flags, void* uargs);
SYSCALL_DEF(getrandom, void* buf, long buflen, unsigned int flags);
SYSCALL_DEF(memfd_create, const char* uname, unsigned int flags);
SYSCALL_DEF(bpf, int cmd, void* attr, unsigned int size);
SYSCALL_DEF(execveat, int dfd, const char* filename, const char* const* argv, const char* const* envp, int flags);
SYSCALL_DEF(socket, int domain, int type, int protocol, int, int, int);
SYSCALL_DEF(socketpair, long domain, long type, long protocol, int* sv, int, int);
SYSCALL_DEF(bind, int fd, const struct sockaddr* addr, int addrlen, int, int, int);
SYSCALL_DEF(connect, int fd, const struct sockaddr* addr, int addrlen, int, int, int);
SYSCALL_DEF(listen, int fd, int backlog, int, int, int, int);
SYSCALL_DEF(accept4, int fd, struct sockaddr* addr, int* addrlen, int, int, int);
SYSCALL_DEF(getsockopt, int fd, int level, int optname, void* optval, int* optlen, int);
SYSCALL_DEF(setsockopt, int fd, int level, int optname, void* optval, int optlen, int);
SYSCALL_DEF(getsockname, int fd, struct sockaddr* addr, int addrlen, int, int, int);
SYSCALL_DEF(getpeername, int fd, struct sockaddr* addr, int* addrlen, int, int, int);
SYSCALL_DEF(sendto, int fd, void* buf, int count, int flags, struct sockaddr* addr, int addrlen);
SYSCALL_DEF(sendmsg, int fd, struct msghdr* msg, unsigned flags, int, int, int);
SYSCALL_DEF(recvfrom, int fd, void* buf, int count, int flags, struct sockaddr* addr, int* addrlen);
SYSCALL_DEF(recvmsg, int fd, struct msghdr* msg, int flags, int, int, int);
SYSCALL_DEF(shutdown, int fd, int how, int, int, int, int);
SYSCALL_DEF(userfaultfd, int flags);
SYSCALL_DEF(membarrier, int cmd, unsigned int flags);
SYSCALL_DEF(mlock2, unsigned long start, long len, int flags);
SYSCALL_DEF(copy_file_range, int fd_in, long* off_in, int fd_out, long* off_out, long len, unsigned int flags);
SYSCALL_DEF(preadv2, int fd, const void* vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h, int flags);
SYSCALL_DEF(pwritev2, int fd, const void* vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h, int flags);
SYSCALL_DEF(pkey_mprotect, unsigned long start, long len, unsigned long prot, int pkey);
SYSCALL_DEF(pkey_alloc, unsigned long flags, unsigned long init_val);
SYSCALL_DEF(pkey_free, int pkey);
SYSCALL_DEF(statx, int dfd, const char* path, unsigned flags, unsigned mask, void* buffer);
SYSCALL_DEF(arch_prctl, int option, unsigned long arg2);
SYSCALL_DEF(io_pgetevents, long ctx_id, long min_nr, long nr, void* events, void* timeout, const void* sig);
SYSCALL_DEF(rseq, void* rseq, unsigned int rseq_len, int flags, unsigned int sig);
SYSCALL_DEF(semget, int key, int nsems, int semflg);
SYSCALL_DEF(semctl, int semid, int semnum, int cmd, unsigned long arg);
SYSCALL_DEF(shmget, int key, long size, int flag);
SYSCALL_DEF(shmctl, int shmid, int cmd, void* buf);
SYSCALL_DEF(shmat, int shmid, char* shmaddr, int shmflg);
SYSCALL_DEF(shmdt, char* shmaddr);
SYSCALL_DEF(msgget, int key, int msgflg);
SYSCALL_DEF(msgsnd, int msqid, void* msgp, long msgsz, int msgflg);
SYSCALL_DEF(msgrcv, int msqid, void* msgp, long msgsz, long msgtyp, int msgflg);
SYSCALL_DEF(msgctl, int msqid, int cmd, void* buf);
SYSCALL_DEF(clock_gettime64, int clk_id, struct timespec* res);
SYSCALL_DEF(clock_settime64, int clk_id, const struct timespec* tp);
SYSCALL_DEF(clock_adjtime64, int which_clock, void* tx);
SYSCALL_DEF(clock_getres_time64, int clk_id, struct timespec* res);
SYSCALL_DEF(clock_nanosleep_time64, int clock_id, int flags, const struct timespec* t, struct timespec* remain);
SYSCALL_DEF(timer_gettime64, int timer_id, void* setting);
SYSCALL_DEF(timer_settime64, int timer_id, int flags, const void* new_setting, void* old_setting);
SYSCALL_DEF(timerfd_gettime64, int ufd, void* otmr);
SYSCALL_DEF(timerfd_settime64, int ufd, int flags, const void* utmr, void* otmr);
SYSCALL_DEF(utimensat_time64, int dirfd, const char* pathname, const void* times, int flags);
SYSCALL_DEF(pselect6_time64, int nfds, void* readfds, void* writefds, void* exceptfds, void* timeout, void* sigmask);
SYSCALL_DEF(ppoll_time64, void* fds, long nfds, void* timeout, const void* sigmask, long sigsetsize);
SYSCALL_DEF(io_pgetevents_time64, long ctx_id, long min_nr, long nr, void* events, void* timeout, const void* sig);
SYSCALL_DEF(recvmmsg_time64, int fd, void* msg, unsigned int vlen, unsigned flags, void* timeout);
SYSCALL_DEF(mq_timedsend_time64, int mqdes, const char* msg_ptr, long msg_len, unsigned int msg_prio, const void* abs_timeout);
SYSCALL_DEF(mq_timedreceive_time64, int mqdes, char* msg_ptr, long msg_len, unsigned int* msg_prio, const void* abs_timeout);
SYSCALL_DEF(semtimedop_time64, int semid, void* sops, unsigned nsops, const void* timeout);
SYSCALL_DEF(rt_sigtimedwait_time64, const void* uthese, void* uinfo, const void* uts, long sigsetsize);
SYSCALL_DEF(sched_rr_get_interval_time64, int pid, void* interval);
SYSCALL_DEF(pidfd_send_signal, int pidfd, int sig, void* info, unsigned int flags);
SYSCALL_DEF(io_uring_setup, unsigned int entries, void* params);
SYSCALL_DEF(io_uring_enter, unsigned int fd, unsigned int to_submit, unsigned int min_complete, unsigned int flags, const void* sig, long sigsz);
SYSCALL_DEF(io_uring_register, unsigned int fd, unsigned int opcode, void* arg, unsigned int nr_args);
SYSCALL_DEF(open_tree, int dfd, const char* pathname, unsigned flags);
SYSCALL_DEF(move_mount, int from_dfd, const char* from_pathname, int to_dfd, const char* to_pathname, unsigned int flags);
SYSCALL_DEF(fsopen, const char* fs_name, unsigned int flags);
SYSCALL_DEF(fsconfig, int fd, unsigned int cmd, const char* key, const void* value, int aux);
SYSCALL_DEF(fsmount, int fd, unsigned int flags, unsigned int ms_flags);
SYSCALL_DEF(fspick, int dfd, const char* pathname, unsigned int flags);
SYSCALL_DEF(pidfd_open, int pid, unsigned int flags);
SYSCALL_DEF(clone3, void* uargs, long size);
SYSCALL_DEF(close_range, unsigned int fd, unsigned int max_fd, unsigned int flags);
SYSCALL_DEF(openat2, int dfd, const char* pathname, void* how, long size);
SYSCALL_DEF(pidfd_getfd, int pidfd, int targetfd, unsigned int flags);
SYSCALL_DEF(faccessat2, int dirfd, const char *pathname, int mode, int flags);
SYSCALL_DEF(process_madvise, int pidfd, const void* vec, long vlen, int behavior, unsigned int flags);

#ifdef __SYSCALL_DEF_DECL
#undef SYSCALL_DEF
#undef __SYSCALL_ATTR
#undef __SYSCALL_DEF_DECL
#endif

//#define VDSO_USEFUL
//#define VDSO_CGT32_SYM "__vdso_clock_gettime"
//#define VDSO_CGT32_VER "LINUX_2.6"
//#define VDSO_CGT_SYM "__vdso_clock_gettime64"
//#define VDSO_CGT_VER "LINUX_2.6"
